# Generated by Django 3.2.11 on 2022-04-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=120, unique=True)),
                ('loction', models.CharField(max_length=120, unique=True)),
                ('slot', models.PositiveIntegerField(default=50)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
